# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20170917_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
