# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20170917_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='city',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='job',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
