# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20170917_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='email',
            field=models.EmailField(max_length=80, unique=True),
        ),
    ]
