# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='job',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='surname',
            field=models.CharField(max_length=255),
        ),
    ]
