# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20170927_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialuser',
            name='friend',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
