# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='b_day',
        ),
    ]
