# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_auto_20171013_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
