# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments_photo', to='social.UserProfile'),
        ),
    ]
