# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 14:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0018_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='interests',
            name='user_interests',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to=settings.AUTH_USER_MODEL),
        ),
    ]
